### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Rush-er** [jr0w3/GLPI_install_script#3]
I found out that the command proposed by the installer not works
![image](https://github.com/jr0w3/GLPI_install_script/assets/32925370/c4895d59-3bc8-453c-830d-2f4441eb5bc0)

With this in the other all works correctly
`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -p -u root mysql`

[Reference](https://glpi-install.readthedocs.io/en/latest/timezones.html#non-windows-users)

**Comment by jr0w3** [comment]
Fixed in 177a806f9b0aa6e9c801f7f80e6e6790626d7af1

**Comment by jr0w3** [comment]
Fixed in 177a806f9b0aa6e9c801f7f80e6e6790626d7af1
